baseURL = 'https://sksg.github.io/orsum-lang/'
languageCode = 'en-us'
title = "Journal, notes, and blog"
theme = 'paperesque'

[taxonomies]
  subject = 'subjects'

[[params.topmenu]]
  name = "see all posts"
  url = "posts/"

[[params.topmenu]]
  name = "choose subject"
  url = "subjects/"

